version: "3"

services: 
  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on: 
      - db
    command: python manage.py runserver 0:8000
    volumes:
      - "./whirlpkgs:/src"
  db:
    env_file: .env
    image: postgres
    restart: always
    ports:
      - "5432"
    volumes:
      - "./db/:/var/lib/postgresql/"

